version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:coverage
            - run:
                name: post coverage
                command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
workflows:
    build-and-test:
      jobs:
        - build-and-test